kafka_version: "3.7.0"
scala_version: "2.13"

kafka_full_version: "kafka_{{ scala_version }}-{{ kafka_version }}"
kafka_tar_file: "{{ kafka_full_version }}.tgz"
kafka_download_url: "http://archive.apache.org/dist/kafka/{{ kafka_version }}/{{ kafka_tar_file }}"

kafka_home: "/opt/kafka"
kafka_bin_dirs: "{{ kafka_home }}/bin"
kafka_config_dirs: "{{ kafka_home }}/config/kraft"
kafka_log_dirs: "/tmp/kraft-combined-logs"

kafka_cluster_id: "4L6g3nShT-eMCtK--X86sw"

kafka_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xms512m -Xmx512m"
  JMX_PORT: "9999"
